/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDialog: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/ui/AppDialog.vue')['default']
    AvatarUpload: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/ui/AvatarUpload.vue')['default']
    Breadcrumb: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/FileManager/components/Breadcrumb.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    ConfirmDialogComponent: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/ui/ConfirmDialogComponent.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EditorColorPalette: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/FormBuilder/inputs/EditorColorPalette.vue')['default']
    EditorImagePicker: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/FormBuilder/inputs/EditorImagePicker.vue')['default']
    EditorInput: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/FormBuilder/inputs/EditorInput.vue')['default']
    FileDetailsDialog: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/FileManager/components/FileDetailsDialog.vue')['default']
    FileGrid: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/FileManager/components/FileGrid.vue')['default']
    FileManager: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/FileManager/FileManager.vue')['default']
    FileManagerSidebar: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/FileManager/components/FileManagerSidebar.vue')['default']
    FileManagerStats: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/FileManager/components/FileManagerStats.vue')['default']
    FilePreviewModal: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/ui/FilePreviewModal.vue')['default']
    FolderTree: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/FileManager/components/FolderTree.vue')['default']
    FolderTreeNode: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/FileManager/components/FolderTreeNode.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    ImageLightbox: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/ui/ImageLightbox.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputOtp: typeof import('primevue/inputotp')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    MimePickerField: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/ui/MimePickerField.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    PageLoading: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/Skeleton/PageLoading.vue')['default']
    Password: typeof import('primevue/password')['default']
    Popover: typeof import('primevue/popover')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SkColorSelector: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/FormBuilder/SkColorSelector.vue')['default']
    SkDatatable: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/DatatableBuilder/SkDatatable.vue')['default']
    SkeletonBox: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/Skeleton/SkeletonBox.vue')['default']
    SkeletonCard: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/Skeleton/SkeletonCard.vue')['default']
    SkeletonTable: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/Skeleton/SkeletonTable.vue')['default']
    SkeletonText: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/Skeleton/SkeletonText.vue')['default']
    SkForm: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/FormBuilder/SkForm.vue')['default']
    SkFormFieldRenderer: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/FormBuilder/SkFormFieldRenderer.vue')['default']
    SkFormInput: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/FormBuilder/SkFormInput.vue')['default']
    SkIcon: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/ui/SkIcon.vue')['default']
    SkTabs: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/TabBuilder/SkTabs.vue')['default']
    SkTag: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/ui/SkTag.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    ToastComponent: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/ui/ToastComponent.vue')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    ToggleFeatureCard: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/ui/ToggleFeatureCard.vue')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    TranslatableInput: typeof import('./vendor/lvntr/laravel-starter-kit/resources/js/components/Lvntr-Starter-Kit/FormBuilder/inputs/TranslatableInput.vue')['default']
    TurnstileWidget: typeof import('./resources/js/components/Auth/TurnstileWidget.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
